#NUMPY

In [1]:
import numpy as np

### Print out the dimension (number of axes), shape, size and the datatype of the matrix A.

In [2]:
A = np.arange(1, 16).reshape(3,5)

# answer 1

In [3]:
# Define matrices B and C
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3)) * 2

# Print matrices B and C
print("Matrix B:")
print(B)
print()

print("Matrix C:")

# Elementwise multiplication
elementwise_multiplication = B * C
print("Elementwise Multiplication (B * C):")
print(elementwise_multiplication)
print()

# Matrix multiplication using @ operator
matrix_multiplication = B @ C
print("Matrix Multiplication (B @ C):")
print(matrix_multiplication)
print(C)
print()

# Elementwise subtraction
elementwise_subtraction = B - C
print("Elementwise Subtraction (B - C):")
print(elementwise_subtraction)
print()

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix C:
Elementwise Multiplication (B * C):
[[ 2.  4.  6.]
 [ 8. 10. 12.]
 [14. 16. 18.]]

Matrix Multiplication (B @ C):
[[12. 12. 12.]
 [30. 30. 30.]
 [48. 48. 48.]]
[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]

Elementwise Subtraction (B - C):
[[-1.  0.  1.]
 [ 2.  3.  4.]
 [ 5.  6.  7.]]



### Do the following computations on the matrices B and C: 
* Elementwise subtraction. 
* Elementwise multiplication. 
* Matrix multiplication (by default you should use the @ operator).

In [4]:
B = np.arange(1, 10).reshape(3, 3)
C = np.ones((3, 3))*2

print(B)
print()
print(C)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[[2. 2. 2.]
 [2. 2. 2.]
 [2. 2. 2.]]


# Answer2

In [5]:

# Create matrix B
B = np.arange(1, 10).reshape(3, 3)

# Print the matrix B
print("Matrix B:")
print(B)
print()

# 1. Exponentiate each number elementwise (np.exp)
exp_B = np.exp(B)
print("Exponentiate each element in B (np.exp):")
print(exp_B)
print()

# 2. Calculate the minimum value in the whole matrix
min_value = np.min(B)
print("Minimum value in the whole matrix:")
print(min_value)
print()

# 3. Calculate the minimum value in each row
min_row_values = np.min(B, axis=1)
print("Minimum value in each row:")
print(min_row_values)
print()

# 4. Calculate the minimum value in each column
min_col_values = np.min(B, axis=0)
print("Minimum value in each column:")
print(min_col_values)
print()

# 5. Find the index of the minimum value in the whole matrix (np.argmin)
min_index = np.argmin(B)
print("Index of the minimum value in the whole matrix:")
print(min_index)
print()

# 6. Find the index of the minimum value in each row (np.argmin)
min_row_indices = np.argmin(B, axis=1)
print("Index of the minimum value in each row:")
print(min_row_indices)
print()

# 7. Calculate the sum for all elements
sum_elements = np.sum(B)
print("Sum of all elements in B:")
print(sum_elements)
print()

# 8. Calculate the mean for each column
mean_col = np.mean(B, axis=0)
print("Mean of each column:")
print(mean_col)
print()

# 9. Calculate the median for each column
median_col = np.median(B, axis=0)
print("Median of each column:")
print(median_col)
print()

Matrix B:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Exponentiate each element in B (np.exp):
[[2.71828183e+00 7.38905610e+00 2.00855369e+01]
 [5.45981500e+01 1.48413159e+02 4.03428793e+02]
 [1.09663316e+03 2.98095799e+03 8.10308393e+03]]

Minimum value in the whole matrix:
1

Minimum value in each row:
[1 4 7]

Minimum value in each column:
[1 2 3]

Index of the minimum value in the whole matrix:
0

Index of the minimum value in each row:
[0 0 0]

Sum of all elements in B:
45

Mean of each column:
[4. 5. 6.]

Median of each column:
[4. 5. 6.]



### Do the following calculations on the matrix:
* Exponentiate each number elementwise (use the np.exp function).

* Calculate the minimum value in the whole matrix. 
* Calculcate the minimum value in each row. 
* Calculcate the minimum value in each column. 


* Find the index value for the minimum value in the whole matrix (hint: use np.argmin).
* Find the index value for the minimum value in each row (hint: use np.argmin).


* Calculate the sum for all elements.
* Calculate the mean for each column. 
* Calculate the median for each column.

In [6]:
B = np.arange(1, 10).reshape(3, 3)
print(B)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


# Answer3

In [7]:
# Create a 2D array A
A = np.arange(1, 16).reshape(3, 5)

# Print the entire matrix A
print("Matrix A:")
print(A)
print()

# Slice using fewer indices, A[1]
print("A[1]:")
print(A[1])

Matrix A:
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]

A[1]:
[ 6  7  8  9 10]


### What does it mean when you provide fewer indices than axes when slicing? See example below.

In [8]:
print(A)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]


In [9]:
A[1]

array([ 6,  7,  8,  9, 10])

# ANSWER4

In [10]:

# Create a 2D array A
A = np.arange(1, 10).reshape(3, 3)

# Iterating over the rows of A
for i in A:
    print(i)


# Iterating over each element in A
for i in np.nditer(A):
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]
1
2
3
4
5
6
7
8
9


### Iterating over multidimensional arrays is done with respect to the first axis, so in the example below we iterate trough the rows. If you would like to iterate through the array *elementwise*, how would you do that?

In [11]:
A

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [12]:
for i in A:
    print(i)

[1 2 3]
[4 5 6]
[7 8 9]


# Answer5

In [13]:
# Iterating over the rows of A
for i in A:
    print(i)


[1 2 3]
[4 5 6]
[7 8 9]


### Explain what the code below does. More specifically, b has three axes - what does this mean? 

In [14]:
a = np.arange(30)
b = a.reshape((2, 3, -1))
print(a)
print()

print(b)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# Answer6

In [15]:
# Create the 1D array 'a' with 30 elements
a = np.arange(30)

# Reshape 'a' into a 3D array 'b' with shape (2, 3, -1)
b = a.reshape((2, 3, -1))

# Print the original array 'a'
print("Array a:")
print(a)
print()

# Print the reshaped 3D array 'b'
print("Array b (reshaped):")
print(b)

Array a:
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

Array b (reshaped):
[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]]

 [[15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]]]


# Vector- and matrix algebra Exercises

**Now you are going to create a function that can be reused every time you add or multiply matrices. The function is created so that we do the addition and multiplication according to the rules of vector- and matrix algebra.**

**Create a function "add_mult_matrices" that takes two matrices as input arguments (validate that the input are of the type numpy.ndarray by using the isinstance function), a third argument that is either 'add' or 'multiply' that specifies if you want to add or multiply the matrices (validate that the third argument is either 'add' or 'multiply'). When doing matrix addition, validate that the matrices have the same size. When doing matrix multiplication, validate that the sizes conform (i.e. number of columns in the first matrix is equal to the number of rows in the second matrix).**

# Answer7

In [16]:

def add_mult_matrices(matrix1, matrix2, operation):
    """
    This function performs matrix addition or multiplication based on the provided operation.
    
    Parameters:
    - matrix1: The first matrix (numpy.ndarray).
    - matrix2: The second matrix (numpy.ndarray).
    - operation: A string specifying whether to 'add' or 'multiply' the matrices.
    
    Returns:
    - Result of the matrix addition or multiplication.
    """
    
    # Validate that the inputs are numpy arrays
    if not isinstance(matrix1, np.ndarray) or not isinstance(matrix2, np.ndarray):
        raise ValueError("Both inputs must be of type numpy.ndarray")
    
    # Validate the operation input
    if operation not in ['add', 'multiply']:
        raise ValueError("The operation must be either 'add' or 'multiply'")
    
    if operation == 'add':
        # Validate that the matrices have the same shape for addition
        if matrix1.shape != matrix2.shape:
            raise ValueError("Matrices must have the same shape for addition")
        return matrix1 + matrix2
    
    elif operation == 'multiply':
        # Validate matrix dimensions for multiplication
        if matrix1.shape[1] != matrix2.shape[0]:
            raise ValueError("Number of columns in the first matrix must match the number of rows in the second matrix")
        return matrix1 @ matrix2

# Example matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Example usage of the function
try:
    result_add = add_mult_matrices(matrix1, matrix2, 'add')
    print("Matrix Addition Result:\n", result_add)
except ValueError as e:
    print(e)

try:
    result_mult = add_mult_matrices(matrix1, matrix2, 'multiply')
    print("\nMatrix Multiplication Result:\n", result_mult)
except ValueError as e:
    print(e)


Matrix Addition Result:
 [[ 6  8]
 [10 12]]

Matrix Multiplication Result:
 [[19 22]
 [43 50]]


### Solve all the exercises in chapter 10.1 in the book "Matematik för yrkeshögskolan". 

# Answer8

In [17]:
import numpy as np

# Define the vector x
x = np.array([4, 3])

# (a) Dimension of the vector x
print(f"(a) Dimension of vector x: {x.shape}")

# (b) Calculate 5x
result_b = 5 * x
print(f"(b) 5x: {result_b}")

# (c) Calculate 3x
result_c = 3 * x
print(f"(c) 3x: {result_c}")

# (d) Calculate 5x + 3x
result_d = 5 * x + 3 * x
print(f"(d) 5x + 3x: {result_d}")

# (e) Calculate 8x
result_e = 8 * x
print(f"(e) 8x: {result_e}")

# (f) Calculate 4x - x
result_f = 4 * x - x
print(f"(f) 4x - x: {result_f}")

# (g) Transpose of vector x (since x is a 1D array, the transpose doesn't change its shape)
x_transposed = np.transpose(x)
print(f"(g) Transposed x: {x_transposed} (No change in shape for a 1D vector)")

# (h) Is x + x^T defined?
try:
    result_h = x + x_transposed
    print(f"(h) x + x^T is defined: {result_h}")
except ValueError as e:
    print(f"(h) x + x^T is not defined: {e}")

# (i) Calculate ||x|| (norm of the vector)
norm_x = np.linalg.norm(x)
print(f"(i) ||x||: {norm_x}")

(a) Dimension of vector x: (2,)
(b) 5x: [20 15]
(c) 3x: [12  9]
(d) 5x + 3x: [32 24]
(e) 8x: [32 24]
(f) 4x - x: [12  9]
(g) Transposed x: [4 3] (No change in shape for a 1D vector)
(h) x + x^T is defined: [8 6]
(i) ||x||: 5.0


### Solve all the exercises, except 10.2.4, in chapter 10.2 in the book "Matematik för yrkeshögskolan". 

# Answer9

In [18]:
import numpy as np

# Define matrices from exercise 10.2.1
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

# (a) 2A
result_a = 2 * A
print(f"(a) 2A:\n{result_a}\n")

# (b) B - 2A
result_b = B - 2 * A
print(f"(b) B - 2A:\n{result_b}\n")

# (c) 3C - 2E (E needs to be broadcast to match dimensions of 3C)
C_expanded = np.array([[1, 2], [2, 1]])  # reshape C as 2x2 for consistency
E_expanded = np.array([[2, 4], [2, 4]])  # broadcast E as 2x2 to match
result_c = 3 * C_expanded - 2 * E_expanded
print(f"(c) 3C - 2E:\n{result_c}\n")

# (d) 2D - 3C
result_d = 2 * D - 3 * C
print(f"(d) 2D - 3C:\n{result_d}\n")

# (e) D^T …
import numpy as np

# Define matrices from exercise 10.2.1
A = np.array([[2, 1, -1], [1, -1, 1]])
B = np.array([[4, -2, 1], [2, -4, -2]])
C = np.array([[1, 2], [2, 1]])
D = np.array([[3, 4], [4, 3]])
E = np.array([[1], [2]])
I = np.array([[1, 0], [0, 1]])

# Exercise 10.2.1

# (a) 2A
result_a = 2 * A
print(f"(a) 2A:\n{result_a}\n")

# (b) B - 2A
result_b = B - 2 * A
print(f"(b) B - 2A:\n{result_b}\n")

# (c) 3C - 2E
# Here, we need to expand E to be able to subtract it from C.
E_expanded = np.array([[2, 4], [2, 4]])  # Adjust E to match dimensions
result_c = 3 * C - 2 * E_expanded
print(f"(c) 3C - 2E:\n{result_c}\n")

# (d) 2D - 3C
# We can subtract C from D as they have the same dimensions.
result_d = 2 * D - 3 * C
print(f"(d) 2D - 3C:\n{result_d}\n")

# (e) D^T + 2D (D^T is the transpose of D)
result_e = D.T + 2 * D
print(f"(e) D^T + 2D:\n{result_e}\n")

# (f) 2C^T - 2D^T
result_f = 2 * C.T - 2 * D.T
print(f"(f) 2C^T - 2D^T:\n{result_f}\n")

# (g) A^T - B
# Transpose A and subtract B
result_g = A.T - B
print(f"(g) A^T - B:\n{result_g}\n")

# (h) AC (matrix product between A and C)
try:
    result_h = np.dot(A, C)  # Use np.dot for matrix product
    print(f"(h) AC:\n{result_h}\n")
except ValueError as e:
    print(f"(h) AC is not defined: {e}\n")

# (i) CD (matrix product between C and D)
try:
    result_i = np.dot(C, D)
    print(f"(i) CD:\n{result_i}\n")
except ValueError as e:
    print(f"(i) CD is not defined: {e}\n")

# (j) CB (matrix product between C and B)
try:
    result_j = np.dot(C, B)
    print(f"(j) CB:\n{result_j}\n")
except ValueError as e:
    print(f"(j) CB is not defined: {e}\n")

# (k) CI (matrix product between C and I, the identity matrix)
result_k = np.dot(C, I)
print(f"(k) CI:\n{result_k}\n")

# (l) AB^T (matrix product between A and the transpose of B)
result_l = np.dot(A, B.T)
print(f"(l) AB^T:\n{result_l}\n")


# Exercise 10.2.2 - Calculate A * A^T
A_2_2 = np.array([[2, 3, 4], [5, 4, 1]])  # Matrix for exercise 10.2.2
result_2_2 = np.dot(A_2_2, A_2_2.T)
print(f"\nExercise 10.2.2 - A * A^T:\n{result_2_2}n")

(a) 2A:
[[ 4  2 -2]
 [ 2 -2  2]]

(b) B - 2A:
[[ 0 -4  3]
 [ 0 -2 -4]]

(c) 3C - 2E:
[[-1 -2]
 [ 2 -5]]

(d) 2D - 3C:
[[3 2]
 [2 3]]

(a) 2A:
[[ 4  2 -2]
 [ 2 -2  2]]

(b) B - 2A:
[[ 0 -4  3]
 [ 0 -2 -4]]

(c) 3C - 2E:
[[-1 -2]
 [ 2 -5]]

(d) 2D - 3C:
[[3 2]
 [2 3]]

(e) D^T + 2D:
[[ 9 12]
 [12  9]]

(f) 2C^T - 2D^T:
[[-4 -4]
 [-4 -4]]



ValueError: operands could not be broadcast together with shapes (3,2) (2,3) 

**Basic indexing creates a view, How can you check if v1 and v2 is a view or copy? If you change the last element in v2 to 123, will the last element in v1 be changed? Why?**

In [36]:
v1 = np.arange(4)
v2 = v1[-2:]
print(v1)
print(v2)

[0 1 2 3]
[2 3]


In [37]:
# The base attribute of a view returns the original array while it returns None for a copy.
print(v1.base)
print(v2.base)

None
[0 1 2 3]


In [38]:
# The last element in v1 will be changed aswell since v2 is a view, meaning they share the same data buffer.
v2[-1] = 123
print(v1)
print(v2)

[  0   1   2 123]
[  2 123]


# Answer10

In [39]:
import numpy as np

# Create an array 'v1'
v1 = np.arange(4)

# Create 'v2' as a slice of 'v1' (this will be a view, not a copy)
v2 = v1[-2:]

# Print the original arrays
print("v1:", v1)
print("v2 (view of v1):", v2)

# Check the 'base' attribute to see if they share the same data
print("\nBase of v1 (None if original):", v1.base)  # This will be None since 'v1' is the original array
print("Base of v2 (original array if it's a view):", v2.base)  # This will be 'v1' since 'v2' is a view of 'v1'

# Modify the last element of 'v2'
v2[-1] = 123

# Print the arrays again to see the change
print("\nAfter modifying v2:")
print("v1 (original array, modified through view):", v1)
print("v2 (view of v1):", v2)


v1: [0 1 2 3]
v2 (view of v1): [2 3]

Base of v1 (None if original): None
Base of v2 (original array if it's a view): [0 1 2 3]

After modifying v2:
v1 (original array, modified through view): [  0   1   2 123]
v2 (view of v1): [  2 123]
